package view;

import javax.swing.*;
import java.awt.event.KeyEvent;

/**
 * Created by Doherty on 5/5/2015.
 */
public class MainScreenViewport extends Viewport {

    AbstractAction newGameButtonListener;
    AbstractAction loadButtonListener;
    AbstractAction exitButtonListener;

    public MainScreenViewport( AbstractAction newGameButtonListener,
                               AbstractAction loadButtonListener,
                               AbstractAction exitButtonListener )
    {
        super();
        this.newGameButtonListener = newGameButtonListener;
        this.loadButtonListener = loadButtonListener;
        this.exitButtonListener = exitButtonListener;
        initComponents();
        setListeners();
    }

    //Setting all button click listeners, I am also setting some keystroke listeners, just cuz
    @Override
    public void setListeners() {
        newGameButton.addActionListener(newGameButtonListener);
        newGameButton.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_N, 0), "N_pressed");
        newGameButton.getActionMap().put("N_pressed", newGameButtonListener);

        loadGameButton.addActionListener(loadButtonListener);
        loadGameButton.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_L,0), "L_pressed");
        loadGameButton.getActionMap().put("L_pressed", loadButtonListener);

        exitButton.addActionListener(exitButtonListener);
        exitButton.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_E,0), "E_pressed");
        exitButton.getActionMap().put("E_pressed", exitButtonListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newGameButton = new javax.swing.JButton();
        loadGameButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        newGameButton.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        newGameButton.setText("New Game");
        newGameButton.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 0, 1, new java.awt.Color(0, 0, 0)));

        loadGameButton.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        loadGameButton.setText("Load Game");
        loadGameButton.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 0, 1, new java.awt.Color(0, 0, 0)));

        exitButton.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 0, 1, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(loadGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JButton loadGameButton;
    private javax.swing.JButton newGameButton;
    // End of variables declaration//GEN-END:variables
}
