/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author Doherty
 */
public class OptionsScreenViewport extends Viewport {

    private ArrayList<ActionListener> actionListeners;

    /**
     * Creates new form OptionsScreenViewport
     */
    public OptionsScreenViewport(ArrayList<ActionListener> actionListeners) {
        super();
        this.actionListeners = actionListeners;
        initComponents();
        setListeners();
    }

    @Override
    protected void setListeners() {
        int i = 0;
        for (JButton button : getButtonArray()) {
            button.addActionListener(actionListeners.get(i++));
        }
    }

    //How tedious... There must be a better way...
    private ArrayList<JButton> getButtonArray() {
        ArrayList<JButton> buttonList = new ArrayList<JButton>();
        buttonList.add(upButton);
        buttonList.add(leftButton);
        buttonList.add(downButton);
        buttonList.add(rightButton);
        buttonList.add(interactButton);
        buttonList.add(meleeButton);
        buttonList.add(itemButton);
        buttonList.add(mountButton);
        buttonList.add(ability1Button);
        buttonList.add(ability2Button);
        buttonList.add(ability3Button);
        buttonList.add(saveButton);
        buttonList.add(pauseButton);
        return buttonList;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upLabel = new javax.swing.JLabel();
        upButton = new javax.swing.JButton();
        leftLabel = new javax.swing.JLabel();
        leftButton = new javax.swing.JButton();
        downLabel = new javax.swing.JLabel();
        downButton = new javax.swing.JButton();
        rightLabel = new javax.swing.JLabel();
        rightButton = new javax.swing.JButton();
        interactLabel = new javax.swing.JLabel();
        interactButton = new javax.swing.JButton();
        meleeLabel = new javax.swing.JLabel();
        meleeButton = new javax.swing.JButton();
        itemLabel = new javax.swing.JLabel();
        itemButton = new javax.swing.JButton();
        mountLabel = new javax.swing.JLabel();
        mountButton = new javax.swing.JButton();
        ability1Label = new javax.swing.JLabel();
        ability1Button = new javax.swing.JButton();
        ability2Label = new javax.swing.JLabel();
        ability2Button = new javax.swing.JButton();
        ability3Label = new javax.swing.JLabel();
        ability3Button = new javax.swing.JButton();
        saveLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        pauseLabel = new javax.swing.JLabel();
        pauseButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        upLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        upLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        upLabel.setText("Up");
        upLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 1, 1, new java.awt.Color(0, 0, 0)));
        upLabel.setOpaque(true);

        upButton.setBackground(new java.awt.Color(0, 102, 255));
        upButton.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        upButton.setText("W");
        upButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 2, 1, 3, new java.awt.Color(0, 0, 0)));

        leftLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        leftLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftLabel.setText("Left");
        leftLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 1, 1, new java.awt.Color(0, 0, 0)));
        leftLabel.setOpaque(true);

        leftButton.setBackground(new java.awt.Color(0, 102, 255));
        leftButton.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        leftButton.setText("A");
        leftButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 3, new java.awt.Color(0, 0, 0)));

        downLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        downLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        downLabel.setText("Down");
        downLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 1, 1, new java.awt.Color(0, 0, 0)));
        downLabel.setOpaque(true);

        downButton.setBackground(new java.awt.Color(0, 102, 255));
        downButton.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        downButton.setText("S");
        downButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 3, new java.awt.Color(0, 0, 0)));

        rightLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        rightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightLabel.setText("Right");
        rightLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 1, 1, new java.awt.Color(0, 0, 0)));
        rightLabel.setOpaque(true);

        rightButton.setBackground(new java.awt.Color(0, 102, 255));
        rightButton.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        rightButton.setText("D");
        rightButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 3, new java.awt.Color(0, 0, 0)));

        interactLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        interactLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        interactLabel.setText("Interact");
        interactLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 1, 1, new java.awt.Color(0, 0, 0)));
        interactLabel.setOpaque(true);

        interactButton.setBackground(new java.awt.Color(0, 102, 255));
        interactButton.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        interactButton.setText("E");
        interactButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 3, new java.awt.Color(0, 0, 0)));

        meleeLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        meleeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        meleeLabel.setText("Melee");
        meleeLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 1, 1, new java.awt.Color(0, 0, 0)));
        meleeLabel.setOpaque(true);

        meleeButton.setBackground(new java.awt.Color(0, 102, 255));
        meleeButton.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        meleeButton.setText("Q");
        meleeButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 3, new java.awt.Color(0, 0, 0)));

        itemLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        itemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemLabel.setText("Use Item");
        itemLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 1, 1, new java.awt.Color(0, 0, 0)));
        itemLabel.setOpaque(true);

        itemButton.setBackground(new java.awt.Color(0, 102, 255));
        itemButton.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        itemButton.setText("Space");
        itemButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 3, new java.awt.Color(0, 0, 0)));

        mountLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        mountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mountLabel.setText("Mount/Unmount");
        mountLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 1, 1, new java.awt.Color(0, 0, 0)));
        mountLabel.setOpaque(true);

        mountButton.setBackground(new java.awt.Color(0, 102, 255));
        mountButton.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        mountButton.setText("Left Shift");
        mountButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 3, new java.awt.Color(0, 0, 0)));

        ability1Label.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        ability1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ability1Label.setText("Ability 1");
        ability1Label.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 1, 1, new java.awt.Color(0, 0, 0)));
        ability1Label.setOpaque(true);

        ability1Button.setBackground(new java.awt.Color(0, 102, 255));
        ability1Button.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        ability1Button.setText("1");
        ability1Button.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 3, new java.awt.Color(0, 0, 0)));

        ability2Label.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        ability2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ability2Label.setText("Ability 2");
        ability2Label.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 1, 1, new java.awt.Color(0, 0, 0)));
        ability2Label.setOpaque(true);

        ability2Button.setBackground(new java.awt.Color(0, 102, 255));
        ability2Button.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        ability2Button.setText("2");
        ability2Button.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 3, new java.awt.Color(0, 0, 0)));

        ability3Label.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        ability3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ability3Label.setText("Ability 3");
        ability3Label.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 1, 1, new java.awt.Color(0, 0, 0)));
        ability3Label.setOpaque(true);

        ability3Button.setBackground(new java.awt.Color(0, 102, 255));
        ability3Button.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        ability3Button.setText("3");
        ability3Button.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 3, new java.awt.Color(0, 0, 0)));

        saveLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        saveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveLabel.setText("Quick Save");
        saveLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 1, 1, new java.awt.Color(0, 0, 0)));
        saveLabel.setOpaque(true);

        saveButton.setBackground(new java.awt.Color(0, 102, 255));
        saveButton.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        saveButton.setText("=");
        saveButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 3, new java.awt.Color(0, 0, 0)));

        pauseLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        pauseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pauseLabel.setText("Pause");
        pauseLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 3, 1, new java.awt.Color(0, 0, 0)));
        pauseLabel.setOpaque(true);

        pauseButton.setBackground(new java.awt.Color(0, 102, 255));
        pauseButton.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        pauseButton.setText("P");
        pauseButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 3, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(upLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(upButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(leftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(leftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(downLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(downButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(interactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(interactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(meleeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(meleeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(itemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(mountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ability1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ability1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ability2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ability2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ability3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ability3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pauseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(downLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meleeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meleeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ability1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ability1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ability2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ability2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ability3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ability3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pauseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ability1Button;
    private javax.swing.JLabel ability1Label;
    private javax.swing.JButton ability2Button;
    private javax.swing.JLabel ability2Label;
    private javax.swing.JButton ability3Button;
    private javax.swing.JLabel ability3Label;
    private javax.swing.JButton downButton;
    private javax.swing.JLabel downLabel;
    private javax.swing.JButton interactButton;
    private javax.swing.JLabel interactLabel;
    private javax.swing.JButton itemButton;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JButton leftButton;
    private javax.swing.JLabel leftLabel;
    private javax.swing.JButton meleeButton;
    private javax.swing.JLabel meleeLabel;
    private javax.swing.JButton mountButton;
    private javax.swing.JLabel mountLabel;
    private javax.swing.JButton pauseButton;
    private javax.swing.JLabel pauseLabel;
    private javax.swing.JButton rightButton;
    private javax.swing.JLabel rightLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel saveLabel;
    private javax.swing.JButton upButton;
    private javax.swing.JLabel upLabel;
    // End of variables declaration//GEN-END:variables
}
